import {freshness} from './freshness.js?v=20261005brand1';
import {esc,icon,badge,dateLabel,timeLabel,stages,due,readiness,timeline,taskOpen,today} from './ui.js?v=20261005brand1';

import {gmailCard,linkedinActions} from './channels.js?v=20261005brand1';

const close = `<button class="icon-btn dialog-close" data-action="close" aria-label="Close dialog">${icon('close')}</button>`;
const feedbackNames = {core:'Your experience',issue:'Report an issue',outcome:'Outreach outcome',value:'Product value'};

export function detail(job, tab='overview', email='', plansAvailable=true) {
  return `<header class="dialog-header"><span class="eyebrow">${esc(job.company)} / ${esc(job.location)}</span>${close}</header><div class="detail-heading"><h2 id="detail-title">${esc(job.title)}</h2><div class="card-pills">${badge(job.stage,'strong')}${job.dashboard||job.stopOutreach?badge(readiness(job)):''}</div><p class="small muted">${job.tracked===false?'First outreach recorded':'Saved'} ${dateLabel(job.createdAt)} · Updated ${dateLabel(job.updatedAt)}</p></div><nav class="detail-tabs" aria-label="Opportunity details">${['overview','activity','evidence'].map(x=>`<button data-action="detail-tab" data-value="${x}" aria-pressed="${tab===x}">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}</nav><div class="detail-content">${tab==='activity'?`<h3>The full story, in order.</h3>${timeline(job.events)}`:tab==='evidence'?evidence(job):overview(job,email,plansAvailable)}</div>`;
}
function overview(j,email,plansAvailable) {
  return `${j.stopOutreach?'<div class="notice"><strong>Outreach stopped</strong><p>This record is closed for outreach. Changing a job stage does not authorize more messages.</p></div>':''}<section class="next-step-box"><div class="section-heading"><span class="eyebrow">YOUR NEXT STEP</span><span class="small">${esc(due(j.planner))}</span></div><h3>${esc(taskOpen(j)?j.planner.title:j.planner?.done?'Step completed':'Make a plan for this job')}</h3><p>${esc(taskOpen(j)?j.planner.reason:'Keep a date and a clear action beside this opportunity.')}</p><div class="button-row">${j.planner?`<button class="btn primary" data-action="complete" data-id="${esc(j.id)}">${icon(j.planner.done?'plus':'check')}${j.planner.done?'Reopen step':'Mark step complete'}</button>`:''}<button class="btn" data-action="schedule" ${!plansAvailable?'disabled':''} data-id="${esc(j.id)}">${icon('calendar')}${j.planner?'Edit plan':'Plan a step'}</button></div></section><div class="section-heading"><h3>Application</h3><button class="text-btn" data-action="edit-stage" data-id="${esc(j.id)}">Update stage ${icon('arrow')}</button></div><div class="button-row"><button class="btn" data-action="apply" data-id="${esc(j.id)}">Open application ${icon('out')}</button></div><div class="fact-row"><span>${j.tracked===false?'Application stage not reported':'Stage · reported by you'}</span><strong>${esc(j.stage)}</strong></div><div class="fact-row"><span>Outcome date</span><strong>${dateLabel(j.outcome_date)}</strong></div><div class="section-heading"><h3>Outreach</h3><span class="small muted">Separate from application status</span></div>${channels(j,email)}<div class="section-heading"><h3>Notes</h3></div><form data-form="note" data-id="${esc(j.id)}"><label class="sr-only" for="job-note">Your notes</label><textarea id="job-note" name="note" rows="3" maxlength="2000" placeholder="Interview details, questions, or something to remember...">${esc(j.note)}</textarea><div class="form-footer"><span class="small muted">Private to your account${j.tracked===false?' · saves this job':''}</span><button class="btn" type="submit">Save note</button></div></form>`;
}
export function channels(j,email='') {
  const gmail = j.gmail.length ? j.gmail.map(s=>`<div class="channel-record">${gmailCard(s)}</div>`).join(''):'<p class="small muted">No Gmail outreach recorded.</p>';
  const li = j.linkedin.length ? j.linkedin.map(a=>`<div class="channel-record"><div class="section-heading"><strong>${esc(a.recipient_name)}</strong>${badge(String(a.state||'unknown').replaceAll('_',' '))}</div><p class="small">${a.messaged_at?'Opening message sent '+dateLabel(a.messaged_at):a.invited_at?'Connection request sent '+dateLabel(a.invited_at):'No sent request recorded.'}</p><p class="small muted">${a.replied_at?'Reply recorded '+dateLabel(a.replied_at):'No reply recorded. Continue conversations in LinkedIn.'}</p>${a.outcome?`<p class="small">Outcome reported by you: ${esc(a.outcome)}</p>`:''}${freshness(a.monitoring,null,'linkedin')}${linkedinActions(a)}</div>`).join(''):'<p class="small muted">No LinkedIn outreach recorded.</p>';
  return `<section class="channel"><h4>${icon('mail')} Gmail</h4>${gmail}</section><section class="channel"><h4><span class="li-icon">in</span> LinkedIn</h4>${li}</section>`;
}
export function evidence(j) {
  const e=j.enrichment, app=j.dashboard, freshness=e.freshness;
  return `<div class="notice"><span class="eyebrow">APPLICATION READINESS</span><h3>${esc(readiness(j))}</h3><p>Evidence and missing answers help you prepare. They do not predict a hiring outcome.</p></div><div class="section-heading"><h3>Job availability</h3>${badge(freshness?.label||'unknown')}</div><p class="small muted">${freshness?.verified_open===true?'Open at the latest check':freshness?.verified_open===false?'Recorded as closed':'Open status is unconfirmed'} · ${dateLabel(freshness?.last_verified_at)}</p><div class="section-heading"><h3>Application packet</h3>${badge(app?.is_packet_approved?'Approval recorded':app?.packet_hash?'Awaiting approval':'Not linked')}</div><div class="file-card">${icon('doc')}<div><strong>${esc(e.resume_filename||'No resume version linked')}</strong><p>${app?.packet_hash?'Saved packet reference: '+esc(app.packet_hash):'Packet details are not linked to this activity record.'}</p></div></div>${app?.packet_hash?'<p class="small muted">Approval belongs to this saved packet. Changed materials require review again.</p>':''}<div class="section-heading"><h3>Requirements & evidence</h3><span class="small muted">${e.requirements?.length||0} shown</span></div>${(e.requirements||[]).map(r=>`<article class="requirement"><div class="section-heading"><strong>${esc(r.text)}</strong>${badge(r.status==='unknown'?'Answer needed':r.status)}</div><p>${esc(r.proof)}</p><div class="evidence-source">${icon('doc')} ${esc(r.evidence_cite)} ${badge(r.badge,'subtle')}</div></article>`).join('')||'<p class="muted">No requirement evidence is linked to this record yet.</p>'}<p class="small muted">Evidence retains its original source labels. Related skills and source groups are context, not verified claims.</p>`;
}

export function editStage(job, initial=null) {
  return `<header class="dialog-header"><span class="eyebrow">${esc(job.company)}</span>${close}</header><h2 id="small-title">Update application stage</h2><p class="muted">${esc(job.title)}. This is your reported application status.</p><form data-form="stage" data-id="${esc(job.id)}"><label>Stage<select name="stage" required>${initial==='choose'||job.tracked===false&&!initial?'<option value="">Choose an application stage</option>':''}${stages.map(s=>`<option ${s===(initial||job.stage)?'selected':''}>${s}</option>`).join('')}</select></label><label>Outcome date <span class="muted">(optional)</span><input type="date" name="outcome_date" value="${esc(job.outcome_date||'')}"></label><label>Note <span class="muted">(optional)</span><textarea name="note" maxlength="2000" rows="3">${esc(job.note)}</textarea></label><div class="form-footer"><span class="small muted">Saved to your account</span><button class="btn primary" type="submit">Save stage</button></div></form>`;
}
export function schedule(job, jobs) {
  const p=job?.planner;
  return `<header class="dialog-header"><span class="eyebrow">YOUR PLAN</span>${close}</header><h2 id="small-title">${p?'Edit your next step':'Plan a next step'}</h2><p class="muted">Give a task a date so it is easy to find again.</p><form data-form="plan">${job?`<input type="hidden" name="job_id" value="${esc(job.id)}"><p><strong>${esc(job.company)}</strong> · ${esc(job.title)}</p>`:`<label>Job<select name="job_id" required><option value="">Choose an opportunity</option>${jobs.filter(j=>!j.stopOutreach).map(j=>`<option value="${esc(j.id)}">${esc(j.company)} · ${esc(j.title)}</option>`).join('')}</select></label>`}<label>Next step<input name="title" maxlength="140" required value="${esc(p?.title||'')}" placeholder="e.g. Prepare for the technical interview"></label><div class="field-pair"><label>Date<input type="date" name="date" required value="${esc(p?.date||today())}"></label><label>Time · IST<input type="time" name="time" required value="${esc(p?.time||'10:00')}"></label></div><label>What should you remember?<textarea name="reason" rows="3" maxlength="500">${esc(p?.reason||'')}</textarea></label><div class="form-footer"><span class="small muted">Saves the job and plan · no automatic reminder</span><button class="btn primary" type="submit">Save plan</button></div></form>`;
}
export function addJob() {
  return `<header class="dialog-header"><span class="eyebrow">SAVE AN OPPORTUNITY</span>${close}</header><h2 id="small-title">Add a job</h2><form data-form="add"><label>Role<input name="title" maxlength="200" required placeholder="e.g. Machine Learning Engineer"></label><label>Company<input name="company" maxlength="200" required placeholder="Company name"></label><label>Job link<input name="url" type="url" maxlength="2000" required placeholder="https://company.com/careers/job"></label><label>Location <span class="muted">(optional)</span><input name="location" maxlength="200" placeholder="City or remote"></label><p id="form-error" role="alert"></p><div class="form-footer"><span class="small muted">Saved to your account</span><button class="btn primary" type="submit">Save job</button></div></form>`;
}
export function feedback(state, kind='core', pane='form') {
  const fields = kind==='core'?state.data.choices:kind==='issue'?{blocker:['Setup','Wrong contact','Former employee','Wrong company or location','Missing email','Wrong draft facts','Draft too generic','Draft tone or length','Sending or login','Slow results','Other']}:kind==='outcome'?{outcome:['Too soon','No response','Delivery failure','Reply without next step','Referral','Recruiter conversation','Interview']}:{disappointment:['Very disappointed','Somewhat disappointed','Not disappointed','Not sure'],purchase:['Yes now','After fixes','After results','Free only','Unsure']};
  const labels={feeling:'How did your latest MiConnects attempt leave you feeling?',contacts:'How often were suggested people worth contacting?',blocker:'What most got in your way?',time:'Compared with your usual process, preparing outreach took...',reuse:'Would you use MiConnects in your next week of job searching?',outcome:'What happened after your outreach? (Reported by you)',disappointment:'How would you feel if MiConnects disappeared?',purchase:'Would you spend your own money on MiConnects?'};
  return `<header class="dialog-header"><span class="eyebrow">MAKE MiConnects BETTER</span>${close}</header><h2 id="feedback-title">Your feedback matters.</h2><p class="muted">Tell us what helped and what got in your way.</p><nav class="detail-tabs" aria-label="Feedback pages"><button data-action="feedback-pane" data-value="form" aria-pressed="${pane==='form'}">Give feedback</button><button data-action="feedback-pane" data-value="history" aria-pressed="${pane==='history'}">History & updates <span>${state.data.feedback.length}</span></button></nav>${pane==='history'?`<div class="feedback-history">${[...state.data.feedback].sort((a,b)=>(b.created_at||" ").localeCompare(a.created_at||" ")).map(f=>`<article><div class="section-heading"><h3>${feedbackNames[f.answers.kind]||'Feedback'}</h3>${badge(f.status)}</div><p class="small muted">${dateLabel(f.created_at)} · ${f.local?'Saved in this browser':'Saved to your account'}</p>${Object.entries(f.answers.choices).map(([k,v])=>`<p><strong>${esc(v)}</strong>${f.answers.comments?.[k]?'<br>'+esc(f.answers.comments[k]):''}</p>`).join('')}${f.published_update?`<div class="owner-update"><span class="eyebrow">MiConnects UPDATE</span><p>${esc(f.published_update)}</p></div>`:'<p class="small muted">No update yet.</p>'}</article>`).join('')}</div>`:`<form data-form="feedback"><label>Feedback type<select id="feedback-kind" name="kind">${Object.entries(feedbackNames).map(([k,v])=>`<option value="${k}" ${kind===k?'selected':''}>${v}</option>`).join('')}</select></label><div class="feedback-questions">${Object.entries(fields).map(([key,choices],i)=>`<fieldset><legend><span>${String(i+1).padStart(2,'0')}</span>${esc(labels[key])}</legend><label class="sr-only" for="choice-${key}">${esc(labels[key])}</label><select id="choice-${key}" name="choice_${key}" required><option value="">Choose an answer</option>${choices.map(c=>`<option>${esc(c)}</option>`).join('')}</select><details><summary>Add context (optional)</summary><textarea name="comment_${key}" aria-label="Optional context for ${esc(key)}" maxlength="500" rows="2"></textarea></details></fieldset>`).join('')}</div><label>Your job search<select name="job_search_status">${['Actively applying','Exploring','Paused','Found a job'].map(x=>`<option>${x}</option>`).join('')}</select></label><label class="check-label"><input type="checkbox" name="followup_consent"> You may follow up with me about this feedback.</label><label class="check-label"><input type="checkbox" name="quote_consent"> You may quote this feedback publicly.</label><div class="form-footer"><span class="small muted">Feedback does not add outreach credits</span><button class="btn primary" type="submit">Save feedback</button></div></form>`}`;
}
